name: Deployment pipeline

on:
    push:
        branches:
            - master

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
            - uses: s2001055/full-stack-open-pokedex@v3.12.12
              with:
                  node-version: '16'
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: 'fullstack-pokedex-app'
                  heroku_email: 'rauhamaa.tomi@gmail.com'
            - name: npm install
              run: npm install
            - name: lint
              run: npm run eslint
            - name: build
              run: npm run build
            - name: test
              run: npm run test
            - name: cypress tests
              uses: cypress-io/github-action@v4
              with:
                  command: npm run build
                  start: npm run start-prod
                  wait-on: http://localhost:5000
